Kajol-Kumari/InfluMart

backend/config/dbConfig.js, backend/controllers/influencerController.js, backend/index.js, backend/middleware/influencers/influencerAuthorizationMiddleware.js, backend/middleware/influencers/influencerLoggingMiddleware.js, backend/model/influencerSignupRequestModel.js, backend/model/influencers.js, backend/package-lock.json, backend/package.json, backend/routes/influencerRoutes.js, backend/utils/influencerAnalytics.js
End point is added. Now you can get the data using that end point. eg: localhost:3000/social/:id
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/2) resolve #2 
[Video Link](https://drive.google.com/file/d/1kSzb6qfw0Wy92O3ltli3i23j4GykX1St/view?usp=drive_link)
api response
=> [Backend] API to Get the influencers data form their Social Handles added

backend/config/dbConfig.js, backend/controllers/subscriptionController.js, backend/index.js, backend/model/Subscription.js, backend/routes/subscriptionRouter.js
I had created 3 endpoint. One is for to show upi url to the user when user click on check out. Here no payment integration is there. For testing only. If user pay the money successfully. Then we will store user data and subscription plan data. If user try to see the profile we will display the data and their taken subscription plan from get endpoints.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/1) resolve #1
=> [Backend] Create Subscription

backend/.env.sample, backend/config/dbConfig.js, backend/constant/constants.js, backend/controllers/otpController.js, backend/index.js, backend/model/otp.js, backend/package-lock.json, backend/package.json, backend/routes/otpRoutes.js
Sending otp and verification of otp via mail is added the routes and funtionality. 
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/13) resolve #13 
https://github.com/Kajol-Kumari/InfluMart/assets/106808387/a11f1924-3354-4d95-8769-ef80e39348cd
I had send you the env variables related to this PR.
=> [Backend] Sending Otp and verification of otp via email for brands added

backend/controllers/subscriptionController.js, backend/routes/subscriptionRouter.js
Created the api endpoint for the get subscription plans.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/4) resolve #4
=> [Backend] Get Subscription Charges API Added

backend/controllers/brandController.js, backend/index.js, backend/middleware/brands/brandAuthenticationMiddleware.js, backend/middleware/brands/validations/brandSignUpValidate.js, backend/model/brandDbRequestModel.js, backend/routes/authRoutes.js, backend/routes/brandRoutes.js
Updated the schema, and integrated that schema into the signup. I had changed the route for band signup why because while trying to signup brand it is giving error your not autherozied. To remove This Problem I created new route where can manage the all signups and login.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/15) resolve #15
=> [Backend] integrating databse to backend for brands

backend/messagingService/README.md
I had added the Readme file to develop the messaging service for the platform. This the conclusion of the discussion
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/3) resolve #3
=> [Discussion] A way Brands can talk to influencers Completed

backend/controllers/brandController.js, frontend/controller/loginController.js, frontend/controller/signupController.js, frontend/package-lock.json, frontend/package.json
It included backend and front end changes. Now from brand sign up -> otp sending -> otp verification -> create account -> login brand. complete work flow is fixed and working.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/42) resolve #42
=> [Backend] Otp Verification issue with Login Brand Fixed

backend/controllers/brandController.js
Encryption and decryption is added. Sign up and login is working for brand.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/44) resolve #44
=> [Bug] The Brand Login and Signup Not as expected Fixed

backend/controllers/collaborationController.js, backend/index.js, backend/middleware/collaborations/collaborationAuthenticationMiddleware.js, backend/middleware/collaborations/collaborationAuthorizationMiddleware.js, backend/model/collaboration.js, backend/routes/collaborationRoutes.js
Fixes #49 
- Created a new collaboration model in `model/collaboration.js`
- Created controllers for collaborations in `controllers/collaborationController.js` that contains functions for creating and retrieving collaborations, getting the minimum requirements and fetching collaboration analytics
- Created API routes associated to collaborations in `routes/collaborationRoutes.js`
@RohitGupta1237 @Kajol-Kumari Please check this PR and suggest any changes if required
P.S: I have made the `model/collaboration.js` considering the models related to brand and influencer, so if you think that some changes are required then please specify them
=> Added API for keeping track of collaborations

frontend/screens/signup/BrandRegistrationForm.js, frontend/screens/signup/SignUpStyles.scss.js
**Issue #24 Fixed**
**Screen Shot**
=> Brand Sign Up Page made as responsive

frontend/screens/BrandorInfluencer.js, frontend/screens/OtpVerification.js
**Issue #56**
**Screenshot**
OTP Verification
BrandOrInfluencer
=> BrandOrInfluencer and OtpVerification page made as responsive

backend/controllers/connectController.js, backend/index.js, backend/model/Message.js, backend/model/Request.js, backend/model/brandDbRequestModel.js, backend/model/influencerSignupRequestModel.js, backend/routes/connectionRoutes.js
Created the models and connection request api. made averything according to the mentioned instructions. If any changes needed please let me know
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/66) resolve #66 
https://github.com/Kajol-Kumari/InfluMart/assets/106808387/2139cc2c-c5ad-4863-9a11-ddca7dc5c270
**Request:** Can you please make this level3 why because creating complete connection request api with all requried endpoints are included. as you have given level3 for pr 51
=> Creating a connect request api at backend added

backend/controllers/brandController.js, frontend/App.js, frontend/controller/signupController.js, frontend/controller/socialController.js, frontend/controller/subscriptionController.js, frontend/screens/BrandAccountSignupDataPreview.js, frontend/screens/Influencer/InfluencerConfirmAccount.js, frontend/screens/Influencer/InfluencerRegistrationForm.js, frontend/screens/Influencer/PlanChooseInterface.js, frontend/screens/OtpVerification.js, frontend/screens/login/LoginPage.js, frontend/screens/login/LoginPageBrands.js, frontend/screens/signup/BrandRegistrationForm.js, frontend/shared/CustomAlert.jsx, frontend/util/AlertContext.js
I had created a useAlert hook. using that we can call the alert at any time we want. I added this alert to all required places or funtionable pages. 
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/65) resolve #65
=> [Frontend] Adding alert notifications Addded

frontend/components/Depth1Frame1.js, frontend/components/Depth1Frame2.js, frontend/components/Depth1Frame3.js, frontend/components/Depth1Frame4.js, frontend/screens/Homepage.js
=> HomePage.js made as responsive

backend/controllers/brandController.js, backend/controllers/influencerController.js, backend/index.js, backend/middleware/brands/validations/brandSignUpValidate.js, backend/model/brandDbRequestModel.js, backend/package-lock.json, backend/package.json, backend/routes/brandRoutes.js, backend/routes/influencerRoutes.js, frontend/App.js, frontend/controller/signupController.js, frontend/package-lock.json, frontend/package.json, frontend/screens/BrandAccountSignupDataPreview.js, frontend/screens/Influencer/InfluencerConfirmAccount.js, frontend/screens/Influencer/InfluencerRegistrationForm.js, frontend/screens/Influencer/InfluencerRegstrationForm.scss.js, frontend/screens/Influencer/components/AddHandles.js, frontend/screens/Influencer/components/MaxFollowersNo.js, frontend/screens/Influencer/components/PricePerPost.js, frontend/screens/Influencer/components/UserProfilePhoto.js, frontend/screens/Influencer/components/UserProfilePhoto.scss.js
Added the multer in backend and changed frontend brand signup and influencer sign up to upload image and changed schema to accept the url.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/73) resolve #73
=> [Backend] Changing Brands and influencer db schema so that profile photo can be saved in db for both Added

frontend/components/Depth1Frame7.js, frontend/screens/AccountCreatedSuccessfullyNoti.js, frontend/screens/BrandsAssosciated.js, frontend/screens/FailedPaymentStatus.js
**Issue #25 Fixed**
**Screenshot**
=> FailedPaymentStatus and AccountCreatedSuccessfullyNoti pages made as Responsive

frontend/App.js, frontend/screens/Influencer/InfluencerRegistrationForm.js, frontend/screens/Influencer/InfluencerRegstrationForm.scss.js, frontend/screens/Influencer/components/AddHandle.scss.js, frontend/screens/Influencer/components/AddHandles.js, frontend/screens/Influencer/components/MaxFollowers.scss.js, frontend/screens/Influencer/components/MaxFollowersNo.js, frontend/screens/Influencer/components/PricePerPost.js, frontend/screens/Influencer/components/PricePerPost.scss.js, frontend/screens/Influencer/components/UserProfilePhoto.js, frontend/screens/Influencer/components/UserProfilePhoto.scss.js, frontend/screens/signup/components/HeadingDescToggle.jsx, frontend/screens/signup/components/InfluPrice.jsx
**Issue #79  Fixed**
**Following Pages made as responsive**
=> InfluencerRegistrationForm and related pages made as responsive

frontend/package-lock.json, frontend/package.json, frontend/screens/BrandAccountSignupDataPreview.js, frontend/screens/BrandAccountSignupDataPreview.scss.js, frontend/screens/Influencer/InfluencerConfirmAccount.js, frontend/screens/Influencer/InfluencerConfirmAccount.scss.js, frontend/screens/Influencer/InfluencerRegistrationForm.js, frontend/screens/Influencer/InfluencerRegstrationForm.scss.js, frontend/screens/Influencer/components/UserProfilePhoto.js, frontend/screens/login/LoginPage.js, frontend/screens/login/LoginPageBrands.js, frontend/screens/login/LoginStyle.js, frontend/screens/signup/BrandRegistrationForm.js, frontend/screens/signup/SignUpStyles.scss.js, frontend/util/imagePickerUtil.js
All mentioned changes are made. I had most of the refactoring done as much as possible. 
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/86) resolve #86
=> [FrontEnd] preview page show hide and refactor preview Fixed

backend/controllers/brandController.js, backend/middleware/brands/brandAuthenticationMiddleware.js, backend/routes/collaborationRoutes.js, frontend/controller/collabrationController.js, frontend/controller/loginController.js, frontend/package-lock.json, frontend/package.json, frontend/screens/BrandProfile.js, frontend/screens/BrandProfile.scss.js
Brand profile page is responsive and refactored, collabration integration was done.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/52) resolve #52
=> [Frontend] Integration of API for keeping track of collaborations with brandprofile page and making page responsive fixed

backend/controllers/brandController.js, backend/routes/brandRoutes.js, frontend/controller/brandController.js, frontend/screens/BrandProfile.js, frontend/screens/BrandProfile.scss.js
get brand profile api is done. and integrated with frontend.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/81)   resolve #81
=> [Frontend] Integration Get Profile Page for Brand fixed

frontend/screens/AdminPanel.js
=> AdminPanel.js made as responsive

frontend/components/Depth1Frame11.js, frontend/screens/BrandProfile.js, frontend/screens/BrandProfile.scss.js, frontend/screens/BrandorInfluencer.js, frontend/screens/BrandsAssosciated.js, frontend/screens/Influencer/InfluencerRegistrationForm.js, frontend/screens/Influencer/InfluencerRegstrationForm.scss.js, frontend/screens/login/LoginPage.js, frontend/screens/login/LoginPageBrands.js, frontend/screens/login/LoginStyle.js, frontend/screens/signup/BrandRegistrationForm.js, frontend/screens/signup/SignUpStyles.scss.js
Back button consistency issue fixed.
=> [Frontend] Back button ui consistency fixes

backend/controllers/brandController.js, backend/package-lock.json, backend/package.json, backend/routes/brandRoutes.js
All apis are added.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/82) resolve #82
=> [Backend] Create Missing Brand APIs Added

frontend/App.js, frontend/controller/signupController.js, frontend/screens/Influencer/InfluencerAccountSuccess.js, frontend/screens/Influencer/InfluencerAccountSucess.scss.js
Now the brand sign up flow is same as expected. 
create account-> success notification-> login page -> user profile
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/104) resolve #104
=> [frontend] fix influncer signup flow similar to brand flow added

frontend/screens/BrandorInfluencer.js, frontend/screens/BrandorInfluencer.scss.js, frontend/screens/Influencer/InfluencerConfirmAccount.js, frontend/screens/Influencer/InfluencerConfirmAccount.scss.js, frontend/screens/login/LoginPage.js, frontend/screens/login/LoginPageBrands.js, frontend/screens/login/LoginStyle.js, frontend/screens/signup/BrandRegistrationForm.js, frontend/screens/signup/SignUpStyles.scss.js
terms of condition and privacy policy links to page of app below login button. and brandorinfluencer refactoring
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/110) resolve #110
=> [Frontend] Adding terms of condition and privacy policy page to app below login button Added and  refactored

frontend/components/Depth1Frame9.js, frontend/controller/InfluencerController.js, frontend/controller/loginController.js, frontend/screens/Analytics/Analytics.js, frontend/screens/Analytics/Analytics.scss.js, frontend/screens/Influencer/components/UserProfilePhoto.js
Integration of influencer analytics page is compeleted. 
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/105) resolve #105
=> [Frontend] Integration of analytics.js with backend completely Added

frontend/screens/FriendRequestPage.js
=> Issue #6 Fixed : FriendRequestPage

backend/controllers/connectController.js, frontend/controller/InfluencerController.js, frontend/controller/connectionsController.js, frontend/controller/socialController.js, frontend/screens/FriendRequestPage.js, frontend/screens/UserProfile/ProductCard.js, frontend/screens/UserProfile/UserProfile.js
User profile pagae the flow of connection requests is completed.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/80) resolve #80
=> [frontend] Integration of connect request api at backend with ui Added

frontend/components/Depth1Frame9.js, frontend/screens/Analytics/Analytics.js, frontend/screens/Analytics/Analytics.scss.js, frontend/screens/Analytics/components/MyGraphs/AllGraphs.js, frontend/screens/Analytics/components/MyGraphs/graphs.scss.js, frontend/screens/Analytics/components/stats/AllStats.js, frontend/screens/Analytics/components/stats/stats.scss.js
=> Analytics page made as responsive

backend/middleware/brandorInfluencerAuthenticationMiddleware.js, backend/routes/influencerRoutes.js, frontend/controller/InfluencerController.js, frontend/controller/socialController.js, frontend/screens/Analytics/Analytics.js, frontend/screens/InfluencerList/IncluencerCard.js, frontend/screens/InfluencerList/InfluencersList.js
this includes frontend and backend changes to make analytics pages open for both influencer and brand not for unregistered users. and complete connect flow is working.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/135) resolve #135
=> [Backend] link influncers list of each with their respective analytics page and make connect button work completely on analytics page Fixed

backend/controllers/influencerController.js, frontend/controller/InfluencerController.js, frontend/screens/Influencer/Settings/InfluencerLogout.js, frontend/screens/Influencer/Settings/Support/InfluencerDeleteAccount.js
Integared the backend with with settings. It include both frontend and backend changes.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/106) resolve #106
=> [Frontend] Integrate the Influencer Setting Profile "admin panel" with Backend Added

frontend/components/Depth1Frame.js, frontend/components/Depth1Frame11.js, frontend/components/Depth1Frame13.js, frontend/screens/Analytics/Analytics.js, frontend/screens/BrandsAssosciated.js, frontend/screens/Influencer/InfluencerRegistrationForm.js, frontend/screens/UserProfile/UserProfile.js
flow is now fixed
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/142) resolve #142
=> [backend] fixing page flows Fixed

frontend/controller/brandController.js, frontend/screens/BrandProfile.js, frontend/screens/BrandsAssosciated.js
=>  Integrate list of brands with frontend

frontend/components/BrandProfileBottomBar.js, frontend/components/Depth1Frame11.js, frontend/screens/BrandProfile.js, frontend/screens/BrandsAssosciated.js, frontend/screens/Homepage.js, frontend/screens/InfluencerList/InfluencersList.js, frontend/screens/UserProfile/UserProfile.js
**Issue #145 Fixed**
**The following changes made**
=> Button UI fixed

frontend/App.js, frontend/screens/Brand/BrandAdminPanel.js, frontend/screens/Brand/Settings/BrandAccountManage.js, frontend/screens/Brand/Settings/BrandLogout.js, frontend/screens/Brand/Settings/BrandLogout.scss.js, frontend/screens/Brand/Settings/Support/BrandDeleteAccount.js, frontend/screens/Brand/Settings/Support/BrandDeleteAccount.scss.js, frontend/screens/BrandProfile.js, frontend/screens/Influencer/Settings/Support/InfluencerContactUs.js, frontend/screens/Influencer/Settings/Support/InfluencerHelpCenter.js
Brand Admin panel is add and logout functionality also added.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/141) resolve #141
=> [Frontend] create the Brand Setting Profile "admin panel" ui similar to influcner settings Added

frontend/controller/paymentController.js, frontend/controller/subscriptionController.js, frontend/screens/Influencer/PlanChooseInterface.js, frontend/shared/PlansBox.jsx, frontend/util/paymentFuntions.js
Now Payment is dynamic and working as expected. if payment fails it redirects to select plan page if user want to pay again they can pay. If payment is successful then we verify the payment on successfull verication me make subscription then redirects to create account page.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/155) resolve #155
=> [Backend] Making payment interface flow dynamic with user prefill content data Fixed

frontend/components/Depth1Frame17.js, frontend/components/Depth1Frame9.js, frontend/screens/Analytics/Analytics.js, frontend/screens/BrandProfile.js, frontend/screens/BrandsAssosciated.js, frontend/screens/Influencer/Settings/Support/InfluencerContactUs.js, frontend/screens/InfluencerList/IncluencerCard.js, frontend/screens/InfluencerList/InfluencersList.js, frontend/screens/UserProfile/UserProfile.js, frontend/util/ImageWithFallback.js
Make only login users can see analytics page. not login user not able to see analytics page. And added random avatars if no dp is present in the db. and give access that one influencer can see other influencer details but not allowed to connect. and added credits. created the random image dp component to ensure code optimize. 
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/161) resolve #161
=> [frontend] add a login alert for not logged in user in marketplace and show avtar for those if no dp is there for brand or Influencer Fixed

backend/controllers/brandController.js, backend/controllers/influencerController.js, frontend/controller/signupController.js, frontend/package-lock.json, frontend/package.json, frontend/screens/Influencer/InfluencerConfirmAccount.js, frontend/screens/Influencer/InfluencerRegistrationForm.js, frontend/screens/Influencer/InfluencerRegstrationForm.scss.js, frontend/screens/signup/BrandRegistrationForm.js, frontend/shared/DropDown.jsx
New fields are added for brand and influencer and integrated to brand. 
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/170) resolve #170
=> Integrate new signup form changes with backend and merge conflict issue Fixed

backend/controllers/brandController.js, backend/controllers/influencerController.js, frontend/components/Depth1Frame17.js, frontend/components/Depth1Frame9.js, frontend/screens/Analytics/Analytics.js, frontend/screens/BrandProfile.js, frontend/screens/BrandsAssosciated.js, frontend/screens/Influencer/InfluencerRegistrationForm.js, frontend/screens/InfluencerList/InfluencersList.js, frontend/screens/UserProfile/UserProfile.js, frontend/screens/signup/BrandRegistrationForm.js
all mentioned changed are fixed
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/172) resolve #172
=> [frontend]updating influencer profile , influencer list , brand profle , brand list with names instaed of usernames Fixed

backend/controllers/influencerController.js, backend/routes/influencerRoutes.js, backend/utils/influencerAnalytics.js
all mentioned search filters are added with endpoint to achive complex search with optimization and effiecency.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/46) resolve #46
=> Creating Filtering and searching functionality for list of influencers Added

backend/controllers/connectController.js, backend/index.js, backend/model/Message.js, backend/package-lock.json, backend/package.json, backend/routes/connectionRoutes.js
Established socket connection. created endpoint to close chat. make it as with accepting connection they can able to chat hello message sent for both. while closing socket connection will diconnect. Socket is used for realtime communication. messages are set to auto delete after 3 days.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/40) resolve #40
=> [Backend] A messaging platform between brands and influencers to connect Added

frontend/package-lock.json, frontend/package.json, frontend/screens/FiltersUI.js, frontend/screens/Influencer/InfluencerRegistrationForm.js, frontend/shared/CustomSlider.jsx, frontend/shared/DropDown.jsx
=> Filter page ui fixed

frontend/App.js, frontend/screens/BrandProfile.js, frontend/screens/chat/ChatInterface.js, frontend/screens/chat/ChatStyles.scss.js, frontend/screens/chat/components/MessageInput.js, frontend/screens/inbox/InboxInterface.js, frontend/screens/inbox/InboxInterface.scss.js
Chat, inbox and message input are refactored and interactive. 
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/181) resolve #181
=> making inbox and chat interface ui interactive and refactoring fixed

backend/controllers/brandController.js, backend/controllers/connectController.js, backend/controllers/influencerController.js, backend/middleware/brandorInfluencerAuthenticationMiddleware.js, backend/utils/influencerAnalytics.js, frontend/controller/brandController.js, frontend/controller/loginController.js, frontend/screens/BrandsAssosciated.js, frontend/screens/Influencer/components/AddHandles.js, frontend/screens/InfluencerList/InfluencersList.js
signup and login bug is fixed. In brand list, brand card enhancement with backend changes to get all brands with their collabrations.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/203) resolve #203
=> [bug] fixing signup issue and login issue Fixed

backend/controllers/influencerController.js, frontend/controller/InfluencerController.js, frontend/screens/BrandsAssosciated.js, frontend/screens/FiltersUI.js, frontend/screens/InfluencerList/InfluencersList.js, frontend/shared/CustomSlider.jsx
Integrated the filters ui with backend. Updated the backend according to the ui.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/176) resolve #176
=> integrate ui filter with backend added

frontend/screens/Influencer/InfluencerRegistrationForm.js, frontend/screens/Influencer/PlanChooseInterface.js
3 months 299
6 month 499
12 months 899
Industry association and age not mandatory
Other plans than 6 months are not working in payment  
fixed and added.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/207) resolve #207
=> [bug] influencer registration form bugs fixed

backend/controllers/connectController.js, frontend/controller/connectionsController.js
It includes frontend and backend changes. now names of sender and receiver are showing.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/208) resolve #208
=> [bug] messaging platform bugs  fixed

backend/controllers/CollabOpenController.js, backend/index.js, backend/model/CollabOpening.js, backend/routes/collabOpenRoutes.js
created Api post endpoint were logged in brand can enter data like campaign type, earning capacity, campaign timelines, brands min eligibility criteria, info about where to post, what to include in product review, campaign steps to follow, barter or cashback or payout or voucher, no of influencers to hire, brand description. this information in form and submit it when brand submit this then as a collab opening it will be posted on collab page of app
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/213) resolve #213
=> [backend] create collab post api added

backend/controllers/CollabOpenController.js, backend/routes/collabOpenRoutes.js
A Backend endpoint is added to get list of all openings posted by brands from database.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/214) resolve #214
=> [backend]create a api to get list of all collab posted by brands  added

backend/controllers/CollabOpenController.js, backend/model/CollabOpenRequest.js, backend/model/brandDbRequestModel.js, backend/routes/collabOpenRoutes.js
created all required api endpoints for the brand collab open apply by influencer. and accept, reject apis. with accepting message will autmatically sent.
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/218) resolve #218
=> [backend]making connect request api added

backend/model/CollabOpening.js, backend/routes/collabOpenRoutes.js, frontend/components/BrandProfileBottomBar.js, frontend/controller/collabOpenController.js, frontend/screens/BrandProfile.js, frontend/screens/collabOpen/CollabForm.js, frontend/screens/collabOpen/CollabPost.js
Backend and frontend is integrated for both post colllab and get all collab post by brands
[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/224) resolve #224
=> integrate collab backend apis with ui complete all pages fixed

backend/controllers/influencerController.js, backend/controllers/paymentController.js, backend/controllers/subscriptionController.js, backend/utils/influencerAnalytics.js, frontend/controller/paymentController.js, frontend/controller/signupController.js, frontend/controller/subscriptionController.js
this pr is a test pr to find what is the acctual bug.
=> test pr to find the bug.
